"""
Apple Music Cookie Refresh Module
Performs SRP web login to obtain fresh cookies (including media-user-token).
Adapted from root main.py. Outputs Netscape-format cookies for gamdl.

Usage:
    from auth import refresh_cookies_sync, cookies_json_to_netscape

    cookies = refresh_cookies_sync(email, password)
    cookies_json_to_netscape(cookies, "/app/cookies/cookies.txt")
"""

import base64
import hashlib
import json
import logging
import re
import secrets
import string
import time
import uuid
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import parse_qs, urlencode, urljoin, urlparse

import requests
from bs4 import BeautifulSoup

log = logging.getLogger("apple-music-auth")

# ── SRP constants ──

RFC5054_2048_N_HEX = (
    "AC6BDB41324A9A9BF166DE5E1389582FAF72B6651987EE07FC3192943DB56050"
    "A37329CBB4A099ED8193E0757767A13DD52312AB4B03310DCD7F48A9DA04FD50"
    "E8083969EDB767B0CF6095179A163AB3661A05FBD5FAAAE82918A9962F0B93B8"
    "55F97993EC975EEAA80D740ADBF4FF747359D041D5C33EA71D281E446B14773B"
    "CA97B43A23FB801676BD207A436C6481F1D2B9078717461A5B9D32E688F87748"
    "544523B524B0D57D5EA77A2775D2ECFA032CFBDBF52FB3786160279004E57AE6"
    "AF874E7303CE53299CCC041C7BC308D82A5698F3A8D0C38271AE35F8E9DBFBB6"
    "94B5C803D89F7AE435DE236D525F54759B65E372FCD68EF20FA7111F9E4AFF73"
)
N_INT = int(RFC5054_2048_N_HEX, 16)
G_INT = 2
GROUP_BYTES = len(bytes.fromhex(RFC5054_2048_N_HEX))

# ── Browser fingerprint constants ──

APPLE_WIDGET_KEY = "06f8d74b71c73757a2f82158d5e948ae7bae11ec45fda9a58690f55e35945c51"
APPLE_REDIRECT_URI = "https://music.apple.com"
APPLE_LANGUAGE = "en_us"
APPLE_STOREFRONT = "143441-1,8"
APPLE_OFFERS_STOREFRONT = "143441-15,8"
APPLE_OAUTH_CLIENT_TYPE = "firstPartyAuth"
APPLE_OAUTH_RESPONSE_MODE = "web_message"
APPLE_OAUTH_RESPONSE_TYPE = "code"
MUSIC_HOME_URL = "https://music.apple.com/us/home"
MUSIC_ROOT_URL = "https://music.apple.com/"

USER_AGENT = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/147.0.0.0 Safari/537.36 Edg/147.0.0.0"
)
SEC_CH_UA = '"Microsoft Edge";v="147", "Not.A/Brand";v="8", "Chromium";v="147"'
SEC_CH_UA_PLATFORM = '"Windows"'
SEC_CH_UA_MOBILE = "?0"


def _make_ifd_client_info() -> str:
    """Generate X-Apple-I-FD-Client-Info header with random fingerprint."""
    import json as _json
    return _json.dumps(
        {
            "U": USER_AGENT,
            "L": "en-US",
            "Z": "GMT-05:00",
            "V": "1.1",
            "F": "".join(
                secrets.choice(string.ascii_letters + string.digits + "._")
                for _ in range(120)
            ),
        },
        separators=(",", ":"),
    )


def cookies_json_to_netscape(cookies: dict, output_path: str) -> None:
    """Convert a cookies dict to Netscape HTTP Cookie File format (for gamdl)."""
    lines = ["# Netscape HTTP Cookie File", "# Generated by apple-music-auth", ""]
    for name, value in cookies.items():
        # Apple Music cookies are typically for .apple.com and .music.apple.com
        if name in ("media-user-token", "mut-refresh"):
            domain = ".music.apple.com"
        else:
            domain = ".apple.com"
        include_subdomains = "TRUE"
        path = "/"
        secure = "TRUE"
        expiry = "0"  # session cookie
        lines.append(f"{domain}\t{include_subdomains}\t{path}\t{secure}\t{expiry}\t{name}\t{value}")
    Path(output_path).write_text("\n".join(lines) + "\n", encoding="utf-8")
    log.info(f"Netscape cookies written: {output_path} ({len(cookies)} cookies)")


def refresh_cookies_sync(
    email: str,
    password: str,
    proxy: str | None = None,
) -> dict:
    """
    Perform full Apple Music SRP web login and return cookies dict.
    Raises on auth failure.

    Args:
        email: Apple ID email
        password: Apple ID password
        proxy: Optional SOCKS5 proxy URL (e.g. "socks5://warp-socks:9091")

    Returns:
        dict of cookie name -> value (includes media-user-token)
    """
    session = requests.Session()
    session.headers.update({"User-Agent": USER_AGENT})

    if proxy:
        session.proxies = {"http": proxy, "https": proxy}
        log.info(f"Auth session using proxy: {proxy}")

    common_html_headers = {
        "User-Agent": USER_AGENT,
        "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
        "Accept-Language": "en-US,en;q=0.9",
        "sec-ch-ua": SEC_CH_UA,
        "sec-ch-ua-mobile": SEC_CH_UA_MOBILE,
        "sec-ch-ua-platform": SEC_CH_UA_PLATFORM,
        "Upgrade-Insecure-Requests": "1",
    }

    common_js_headers = {
        "User-Agent": USER_AGENT,
        "Accept": "*/*",
        "Accept-Language": "en-US,en;q=0.9",
        "sec-ch-ua": SEC_CH_UA,
        "sec-ch-ua-mobile": SEC_CH_UA_MOBILE,
        "sec-ch-ua-platform": SEC_CH_UA_PLATFORM,
    }

    # ── Step 1: Seed baseline cookies ──
    log.info("Seeding baseline cookies")
    for domain in (".apple.com", "music.apple.com", ".music.apple.com"):
        session.cookies.set("geo", "US", domain=domain)
        session.cookies.set("dslang", "US-EN", domain=domain)
        session.cookies.set("site", "USA", domain=domain)
        session.cookies.set("itre", "0", domain=domain)

    # ── Step 2: Open Apple Music landing page → extract dev token ──
    log.info("Opening Apple Music landing page")
    resp = session.get(MUSIC_HOME_URL, headers=common_html_headers, timeout=30)
    resp.raise_for_status()
    home_html = resp.text
    home_soup = BeautifulSoup(home_html, "html.parser")

    script_urls = [urljoin(MUSIC_ROOT_URL, t["src"]) for t in home_soup.find_all("script", src=True)]

    dev_token = ""
    m = re.search(r'(eyJ[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+)', home_html)
    if m:
        dev_token = m.group(1)

    for candidate in re.findall(r'https://music\.apple\.com/includes/commerce/[^"\']+', home_html):
        qs = parse_qs(urlparse(candidate).query)
        if qs.get("devToken"):
            dev_token = qs["devToken"][0]
            break

    if not dev_token:
        log.info("Searching scripts for web playback token")
        for script_url in script_urls:
            try:
                r = session.get(script_url, headers={**common_js_headers, "Referer": MUSIC_ROOT_URL}, timeout=30)
                if r.status_code != 200:
                    continue
                tm = re.search(
                    r'(eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IldlYlBsYXlLaWQifQ\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+)',
                    r.text,
                )
                if not tm:
                    tm = re.search(r'devToken["\']?\s*[:=]\s*["\']([^"\']+)["\']', r.text)
                if tm:
                    dev_token = tm.group(1)
                    break
            except requests.RequestException:
                continue

    if not dev_token:
        raise RuntimeError("Apple Music web playback token not found")

    # Validate token
    parts = dev_token.split(".")
    if len(parts) != 3:
        raise RuntimeError("Invalid dev token format")
    payload = json.loads(base64.urlsafe_b64decode(parts[1] + "=" * (-len(parts[1]) % 4)))
    token_exp = int(payload.get("exp", 0) or 0)
    if token_exp and token_exp - int(time.time()) <= 0:
        raise RuntimeError("Dev token expired")

    # ── Step 3: Commerce fetch proxy ──
    log.info("Opening commerce fetch proxy")
    fetch_proxy_params = {
        "product": "music", "devToken": dev_token, "authType": "web",
        "authDisplayType": "inline", "locale": "en-US", "useRelativeIframeSrc": "true",
        "iso2code": "us", "isFullscreen": "true", "hostedAppSubdomain": "music",
    }
    session.get(
        "https://music.apple.com/includes/commerce/fetch-proxy.html?" + urlencode(fetch_proxy_params),
        headers={**common_html_headers, "Referer": MUSIC_ROOT_URL}, timeout=30,
    ).raise_for_status()

    # ── Step 4: Apple sign-in frame ──
    frame_id = f"auth-{uuid.uuid4()}"
    authorize_url = (
        f"https://idmsa.apple.com/appleauth/auth/authorize/signin"
        f"?frame_id={frame_id}&language={APPLE_LANGUAGE}&skVersion=7"
        f"&iframeId={frame_id}&client_id={APPLE_WIDGET_KEY}"
        f"&redirect_uri={APPLE_REDIRECT_URI}&response_type={APPLE_OAUTH_RESPONSE_TYPE}"
        f"&response_mode={APPLE_OAUTH_RESPONSE_MODE}&account_ind=1"
        f"&state={frame_id}&authVersion=latest"
    )

    log.info("Opening sign-in frame")
    resp_auth = session.get(authorize_url, headers={**common_html_headers, "Referer": MUSIC_ROOT_URL}, timeout=30)
    resp_auth.raise_for_status()

    session_id = resp_auth.headers.get("X-Apple-ID-Session-Id", "")
    scnt = resp_auth.headers.get("scnt", "")
    auth_attrs = resp_auth.headers.get("X-Apple-Auth-Attributes", "")
    hc_bits = resp_auth.headers.get("X-Apple-HC-Bits", "")
    hc_challenge = resp_auth.headers.get("X-Apple-HC-Challenge", "")

    auth_soup = BeautifulSoup(resp_auth.text, "html.parser")
    for node in auth_soup.find_all("script", attrs={"class": "boot_args", "type": "application/json"}):
        try:
            p = json.loads(node.get_text(strip=True)).get("direct", {})
        except Exception:
            continue
        if p.get("authAttributes") and not auth_attrs:
            auth_attrs = p["authAttributes"]
        hc = p.get("hashcash", {})
        if isinstance(hc, dict):
            if hc.get("hcBits") and not hc_bits:
                hc_bits = str(hc["hcBits"])
            if hc.get("hcChallenge") and not hc_challenge:
                hc_challenge = hc["hcChallenge"]

    def _apple_headers():
        h = {
            "User-Agent": USER_AGENT,
            "Accept": "application/json, text/javascript, */*; q=0.01",
            "Accept-Language": "en-US,en;q=0.9",
            "Content-Type": "application/json",
            "Origin": "https://idmsa.apple.com",
            "Referer": "https://idmsa.apple.com/",
            "X-Apple-Widget-Key": APPLE_WIDGET_KEY,
            "X-Apple-OAuth-Client-Id": APPLE_WIDGET_KEY,
            "X-Apple-OAuth-Client-Type": APPLE_OAUTH_CLIENT_TYPE,
            "X-Apple-OAuth-Response-Mode": APPLE_OAUTH_RESPONSE_MODE,
            "X-Apple-OAuth-Response-Type": APPLE_OAUTH_RESPONSE_TYPE,
            "X-Apple-OAuth-Redirect-URI": APPLE_REDIRECT_URI,
            "X-Apple-Frame-Id": frame_id,
            "X-Apple-I-FD-Client-Info": _make_ifd_client_info(),
            "X-Requested-With": "XMLHttpRequest",
            "sec-ch-ua": SEC_CH_UA,
            "sec-ch-ua-mobile": SEC_CH_UA_MOBILE,
            "sec-ch-ua-platform": SEC_CH_UA_PLATFORM,
        }
        if session_id:
            h["X-Apple-ID-Session-Id"] = session_id
        if scnt:
            h["scnt"] = scnt
        if auth_attrs:
            h["X-Apple-Auth-Attributes"] = auth_attrs
        if hc_bits:
            h["X-Apple-HC-Bits"] = hc_bits
        if hc_challenge:
            h["X-Apple-HC-Challenge"] = hc_challenge
        return h

    def _music_auth_headers():
        h = {
            "User-Agent": USER_AGENT,
            "Accept": "*/*",
            "Accept-Language": "en-US,en;q=0.9",
            "Content-Type": "application/json",
            "Origin": "https://music.apple.com",
            "Referer": "https://music.apple.com/",
            "x-apple-store-front": APPLE_STOREFRONT,
            "sec-ch-ua": SEC_CH_UA,
            "sec-ch-ua-mobile": SEC_CH_UA_MOBILE,
            "sec-ch-ua-platform": SEC_CH_UA_PLATFORM,
        }
        if session_id:
            h["X-Apple-ID-Session-Id"] = session_id
        if scnt:
            h["scnt"] = scnt
        if auth_attrs:
            h["X-Apple-Auth-Attributes"] = auth_attrs
        if hc_bits:
            h["X-Apple-HC-Bits"] = hc_bits
        if hc_challenge:
            h["X-Apple-HC-Challenge"] = hc_challenge
        return h

    def _update_scnt(resp):
        nonlocal scnt
        if resp.headers.get("scnt"):
            scnt = resp.headers["scnt"]

    # ── Step 5: Federate ──
    log.info("Calling federate")
    r = session.post(
        "https://idmsa.apple.com/appleauth/auth/federate?isRememberMeEnabled=false",
        headers=_apple_headers(), json={"accountName": email, "rememberMe": False}, timeout=30,
    )
    r.raise_for_status()
    _update_scnt(r)

    # ── Step 6: Device challenge ──
    log.info("Calling device challenge")
    r = session.post(
        "https://idmsa.apple.com/appleauth/auth/verify/device/key/challenge",
        headers=_apple_headers(), json={"passkeyAutofill": False}, timeout=30,
    )
    r.raise_for_status()
    _update_scnt(r)

    # ── Step 7: Refresh sign-in frame ──
    log.info("Refreshing sign-in frame")
    frame_id = f"auth-{uuid.uuid4()}"
    authorize_url = (
        f"https://idmsa.apple.com/appleauth/auth/authorize/signin"
        f"?frame_id={frame_id}&language={APPLE_LANGUAGE}&skVersion=7"
        f"&iframeId={frame_id}&client_id={APPLE_WIDGET_KEY}"
        f"&redirect_uri={APPLE_REDIRECT_URI}&response_type={APPLE_OAUTH_RESPONSE_TYPE}"
        f"&response_mode={APPLE_OAUTH_RESPONSE_MODE}&account_ind=1"
        f"&state={frame_id}&authVersion=latest"
    )
    resp_auth = session.get(authorize_url, headers={**common_html_headers, "Referer": MUSIC_ROOT_URL}, timeout=30)
    resp_auth.raise_for_status()

    session_id = resp_auth.headers.get("X-Apple-ID-Session-Id", session_id)
    scnt = resp_auth.headers.get("scnt", scnt)
    auth_attrs = resp_auth.headers.get("X-Apple-Auth-Attributes", auth_attrs)
    hc_bits = resp_auth.headers.get("X-Apple-HC-Bits", hc_bits)
    hc_challenge = resp_auth.headers.get("X-Apple-HC-Challenge", hc_challenge)

    # ── Step 8: Federate again ──
    log.info("Calling federate again")
    r = session.post(
        "https://idmsa.apple.com/appleauth/auth/federate?isRememberMeEnabled=false",
        headers=_apple_headers(), json={"accountName": email, "rememberMe": False}, timeout=30,
    )
    r.raise_for_status()
    _update_scnt(r)

    # ── Step 9: SRP init ──
    log.info("SRP init")
    private_a = secrets.token_bytes(GROUP_BYTES)
    private_a_int = int.from_bytes(private_a, "big")
    public_a_int = pow(G_INT, private_a_int, N_INT)
    public_a_bytes = public_a_int.to_bytes(GROUP_BYTES, "big")

    r = session.post(
        "https://idmsa.apple.com/appleauth/auth/signin/init",
        headers=_apple_headers(),
        json={
            "a": base64.b64encode(public_a_bytes).decode(),
            "accountName": email,
            "protocols": ["s2k", "s2k_fo"],
        },
        timeout=30,
    )
    r.raise_for_status()
    _update_scnt(r)
    init = r.json()

    iterations = int(init["iteration"])
    salt = base64.b64decode(init["salt"])
    server_b = base64.b64decode(init["b"])
    server_b_int = int.from_bytes(server_b, "big")
    c_value = init["c"]

    # ── Step 10: SRP complete ──
    log.info("SRP complete")
    pw_hash = hashlib.sha256(password.encode()).digest()
    pw_derived = hashlib.pbkdf2_hmac("sha256", pw_hash, salt, iterations, dklen=32)
    x = hashlib.sha256(salt + hashlib.sha256(b":" + pw_derived).digest()).digest()
    x_int = int.from_bytes(x, "big")
    k = hashlib.sha256(
        bytes.fromhex(RFC5054_2048_N_HEX) + G_INT.to_bytes(1, "big").rjust(GROUP_BYTES, b"\x00")
    ).digest()
    k_int = int.from_bytes(k, "big")
    u = hashlib.sha256(public_a_bytes + server_b).digest()
    u_int = int.from_bytes(u, "big")
    gx = pow(G_INT, x_int, N_INT)
    base_val = (server_b_int - (k_int * gx)) % N_INT
    exp_val = private_a_int + (u_int * x_int)
    shared = pow(base_val, exp_val, N_INT).to_bytes(GROUP_BYTES, "big")
    shared_key = hashlib.sha256(shared).digest()
    hn = hashlib.sha256(bytes.fromhex(RFC5054_2048_N_HEX)).digest()
    hg = hashlib.sha256(G_INT.to_bytes(1, "big").rjust(GROUP_BYTES, b"\x00")).digest()
    hi = hashlib.sha256(email.lower().encode()).digest()
    xor_ng = bytes(a ^ b for a, b in zip(hn, hg))
    m1 = hashlib.sha256(xor_ng + hi + salt + public_a_bytes + server_b + shared_key).digest()
    m2 = hashlib.sha256(public_a_bytes + m1 + shared_key).digest()

    r = session.post(
        "https://idmsa.apple.com/appleauth/auth/signin/complete?isRememberMeEnabled=false",
        headers=_apple_headers(),
        json={
            "accountName": email,
            "rememberMe": False,
            "m1": base64.b64encode(m1).decode(),
            "c": c_value,
            "m2": base64.b64encode(m2).decode(),
        },
        timeout=30,
    )
    r.raise_for_status()
    _update_scnt(r)

    # ── Step 11: Final auth ──
    log.info("Final auth (auth/v1/web)")
    session.post(
        "https://auth.music.apple.com/auth/v1/web",
        headers=_music_auth_headers(),
        json={"webAuthorizationFlowContext": "music"},
        timeout=30,
    ).raise_for_status()

    # ── Step 12: Account info + auth v2 ──
    music_api_headers = {
        "User-Agent": USER_AGENT,
        "Accept": "*/*",
        "Accept-Language": "en-US,en;q=0.9",
        "Content-Type": "application/json",
        "Origin": "https://music.apple.com",
        "Referer": "https://music.apple.com/",
        "Authorization": f"Bearer {dev_token}",
        "x-apple-store-front": APPLE_STOREFRONT,
        "sec-ch-ua": SEC_CH_UA,
        "sec-ch-ua-mobile": SEC_CH_UA_MOBILE,
        "sec-ch-ua-platform": SEC_CH_UA_PLATFORM,
    }
    mut = session.cookies.get("media-user-token", domain=".music.apple.com") or session.cookies.get("media-user-token")
    if mut:
        music_api_headers["media-user-token"] = mut

    log.info("Refreshing account info")
    session.get("https://buy.music.apple.com/account/web/info", headers=music_api_headers, timeout=30).raise_for_status()
    session.get("https://buy.music.apple.com/account/web/infoRefresh", headers=music_api_headers, timeout=30).raise_for_status()

    log.info("Auth v2")
    session.post(
        "https://auth.music.apple.com/auth/v2/web",
        headers={
            "User-Agent": USER_AGENT, "Accept": "*/*", "Accept-Language": "en-US,en;q=0.9",
            "Origin": "https://music.apple.com", "Referer": "https://music.apple.com/",
            "sec-ch-ua": SEC_CH_UA, "sec-ch-ua-mobile": SEC_CH_UA_MOBILE,
            "sec-ch-ua-platform": SEC_CH_UA_PLATFORM,
        },
        timeout=30,
    ).raise_for_status()

    # Re-read media-user-token after v2 refresh
    mut = session.cookies.get("media-user-token", domain=".music.apple.com") or session.cookies.get("media-user-token")
    if mut:
        music_api_headers["media-user-token"] = mut

    # ── Step 13: Subscription verification ──
    log.info("Verifying subscription")
    session.get(
        "https://amp-api.music.apple.com/v1/me/account",
        params={"art[url]": "f", "challenge[subscriptionCapabilities]": "voice,premium", "meta": "subscription", "platform": "web"},
        headers=music_api_headers, timeout=30,
    ).raise_for_status()

    session.get("https://buy.music.apple.com/account/web/info", headers=music_api_headers, timeout=30).raise_for_status()
    session.get("https://buy.music.apple.com/account/web/infoRefresh", headers=music_api_headers, timeout=30).raise_for_status()

    # ── Step 14: Navigator ──
    log.info("Opening navigator")
    nav_params = {
        "product": "music", "devToken": dev_token, "authType": "web",
        "authDisplayType": "inline", "locale": "en-US", "useRelativeIframeSrc": "true",
        "iso2code": "us", "isModal": "true", "hideCurtain": "true", "hostedAppSubdomain": "music",
    }
    r = session.get(
        "https://music.apple.com/includes/commerce/navigator?" + urlencode(nav_params),
        headers={**common_html_headers, "Referer": MUSIC_ROOT_URL}, timeout=30,
    )
    r.raise_for_status()

    # ── Collect cookies ──
    cookies = {}
    for c in session.cookies:
        cookies[c.name] = c.value

    cookies.setdefault("geo", "US")
    cookies.setdefault("dslang", "US-EN")
    cookies.setdefault("site", "USA")
    cookies.setdefault("itre", "0")

    required = ["media-user-token", "myacinfo", "commerce-authorization-token"]
    missing = [n for n in required if not cookies.get(n)]
    if missing:
        raise RuntimeError(f"Login succeeded but critical cookies missing: {', '.join(missing)}")

    log.info(f"Cookie refresh complete — {len(cookies)} cookies obtained")
    return cookies
